apiVersion: v1
kind: Service
metadata:
  name: my-app-home
spec:
  selector:
    app: my-app-home
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-home-v0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app-home
      version: v0
  template:
    metadata:
      labels:
        app: my-app-home
        version: v0
    spec:
      containers:
      - name: my-app-home
        image: 578310434439.dkr.ecr.ap-northeast-2.amazonaws.com/develop:main-6b7fff9
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-home-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app-home
      version: v1
  template:
    metadata:
      labels:
        app: my-app-home
        version: v1
    spec:
      containers:
      - name: my-app-home
        image: 578310434439.dkr.ecr.ap-northeast-2.amazonaws.com/develop:main-4c3e767
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: my-app-login
spec:
  selector:
    app: my-app-login
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-login-v0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app-login
      version: v0
  template:
    metadata:
      labels:
        app: my-app-login
        version: v0
    spec:
      containers:
      - name: my-app-login
        image: 578310434439.dkr.ecr.ap-northeast-2.amazonaws.com/develop:login-8eae277
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-login-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app-login
      version: v1
  template:
    metadata:
      labels:
        app: my-app-login
        version: v1
    spec:
      containers:
      - name: my-app-login
        image: 578310434439.dkr.ecr.ap-northeast-2.amazonaws.com/develop:login-7101d51
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: my-app-product
spec:
  selector:
    app: my-app-product
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-product-v0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app-product
      version: v0
  template:
    metadata:
      labels:
        app: my-app-product
        version: v0
    spec:
      containers:
      - name: my-app-product
        image: 578310434439.dkr.ecr.ap-northeast-2.amazonaws.com/develop:product-ce278aa
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-product-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app-product
      version: v1
  template:
    metadata:
      labels:
        app: my-app-product
        version: v1
    spec:
      containers:
      - name: my-app-product
        image: 578310434439.dkr.ecr.ap-northeast-2.amazonaws.com/develop:product-d76bc8e
        ports:
        - containerPort: 80