apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollout-bluegreen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rollout-bluegreen
  template:
    metadata:
      name: rollout-bluegreen
      labels:
        app: rollout-bluegreen
    spec:
      containers:
      - name: rollout-bluegreen-container
        image: 578310434439.dkr.ecr.ap-northeast-2.amazonaws.com/develop:main-3410cd3
        ports:
        - containerPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollout-bluegreen-preview
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rollout-bluegreen-preview
  template:
    metadata:
      name: rollout-bluegreen-preview
      labels:
        app: rollout-bluegreen-preview
    spec:
      containers:
      - name: rollout-bluegreen-preview-container
        image: 578310434439.dkr.ecr.ap-northeast-2.amazonaws.com/develop:main-65e6a38
        ports:
        - containerPort: 80