apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  labels:
    run: my-app-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    name: http
  selector:
    run: my-app